const diyKeywords = [
  // 🔨 CORE DIY TERMS
  "diy",
  "do it yourself",
  "handmade",
  "homemade",
  "craft",
  "make",
  "build",
  "create",
  "construct",
  "assemble",
  "fix",
  "repair",
  "restore",
  "modify",
  "upgrade",
  "customize",
  "design",
  "install",
  "renovate",
  "improve",
  "tinker",
  "decorate",
  "upcycle",
  "recycle",
  "What's",
  "repurpose",
  "fabricate",
  "hack",
  "adjust",
  "fabrication",
  "troubleshoot",
  "refurbish",
  "alter",
  "crafting",
  "project",
  "how to",
  "tutorial",
  "guide",
  "instructions",
  "blueprint",
  "schematic",
  "manual",
  "steps",
  "process",
  "method",
  "technique",
  "approach",
  "solution",

  // 📜 MATERIALS
  "paper",
  "cardboard",
  "wood",
  "metal",
  "plastic",
  "fabric",
  "clay",
  "glass",
  "ceramic",
  "resin",
  "epoxy",
  "concrete",
  "plaster",
  "wire",
  "yarn",
  "thread",
  "leather",
  "foam",
  "rubber",
  "stone",
  "brick",
  "tile",
  "vinyl",
  "pvc",
  "acrylic",
  "plywood",
  "mdf",
  "particle board",
  "lumber",
  "sheet metal",
  "aluminum",
  "copper",
  "brass",
  "steel",
  "iron",
  "stainless steel",
  "bronze",

  // 🛠️ TOOLS
  "hammer",
  "saw",
  "drill",
  "screwdriver",
  "wrench",
  "pliers",
  "knife",
  "scissors",
  "glue gun",
  "soldering iron",
  "welder",
  "sewing machine",
  "lathe",
  "router",
  "sander",
  "plane",
  "chisel",
  "file",
  "vise",
  "clamp",
  "measuring tape",
  "level",
  "square",
  "brush",
  "roller",
  "spatula",
  "trowel",
  "needle",
  "hook",
  "loom",
  "pottery wheel",
  "kiln",
  "3d printer",
  "laser cutter",
  "cnc machine",
  "anvil",

  // 🪚 WOODWORKING
  "woodworking",
  "carpentry",
  "joinery",
  "woodturning",
  "carving",
  "whittling",
  "cabinet making",
  "furniture making",
  "wood carving",
  "scroll saw",
  "bandsaw",
  "table saw",
  "miter saw",
  "circular saw",
  "jigsaw",
  "planer",
  "wood lathe",
  "dovetail",
  "mortise",
  "tenon",
  "wood glue",
  "wood finish",
  "stain",
  "varnish",
  "polyurethane",
  "shellac",
  "wood filler",
  "wood putty",
  "sanding",
  "planing",

  // 🏠 HOME IMPROVEMENT
  "home improvement",
  "renovation",
  "remodel",
  "construction",
  "plumbing",
  "electrical",
  "painting",
  "drywall",
  "tiling",
  "flooring",
  "roofing",
  "insulation",
  "carpentry",
  "masonry",
  "landscaping",
  "gardening",
  "decking",
  "fencing",
  "siding",
  "weatherproofing",
  "waterproofing",
  "soundproofing",
  "lighting",
  "smart home",
  "home automation",
  "security system",
  "shelving",
  "storage",
  "organization",
  "closet",
  "kitchen",
  "bathroom",
  "basement",
  "attic",
  "garage",
  "shed",
  "patio",
  "porch",
  "gazebo",
  "pergola",

  // 🔌 ELECTRONICS
  "electronics",
  "circuit",
  "arduino",
  "raspberry pi",
  "soldering",
  "breadboard",
  "pcb",
  "microcontroller",
  "sensor",
  "actuator",
  "motor",
  "servo",
  "stepper",
  "led",
  "display",
  "power supply",
  "battery",
  "solar",
  "inverter",
  "transformer",
  "resistor",
  "capacitor",
  "transistor",
  "diode",
  "relay",
  "switch",
  "potentiometer",
  "oscilloscope",
  "multimeter",
  "signal generator",
  "logic analyzer",
  "robotics",
  "drones",
  "rc",
  "radio control",
  "iot",
  "home automation",
  "smart device",

  // 🧵 TEXTILES & FIBER
  "sewing",
  "knitting",
  "crochet",
  "embroidery",
  "quilting",
  "weaving",
  "spinning",
  "felting",
  "macrame",
  "lace making",
  "tapestry",
  "rug making",
  "basket weaving",
  "leatherworking",
  "tanning",
  "bookbinding",
  "paper making",
  "origami",
  "kirigami",
  "batik",
  "tie dye",
  "screen printing",
  "block printing",
  "fabric painting",
  "garment making",
  "pattern making",
  "tailoring",
  "upholstery",
  "drapery",

  // 🎨 ARTS & CRAFTS
  "painting",
  "drawing",
  "sculpting",
  "pottery",
  "ceramics",
  "mosaics",
  "collage",
  "decoupage",
  "stenciling",
  "calligraphy",
  "lettering",
  "printmaking",
  "engraving",
  "etching",
  "glass blowing",
  "stained glass",
  "jewelry making",
  "beading",
  "wire wrapping",
  "metal smithing",
  "lapidary",
  "resin art",
  "polymer clay",
  "soap making",
  "candle making",
  "cosmetics",
  "perfume making",
  "paper crafts",
  "scrapbooking",
  "card making",
  "model making",
  "miniatures",
  "dioramas",

  // 🚗 AUTOMOTIVE & MECHANICAL
  "auto repair",
  "car maintenance",
  "engine",
  "transmission",
  "brakes",
  "suspension",
  "exhaust",
  "electrical system",
  "body work",
  "painting",
  "detailing",
  "customizing",
  "motorcycle",
  "bicycle",
  "atv",
  "boat",
  "small engine",
  "lawn mower",
  "tractor",
  "welding",
  "fabrication",
  "machining",
  "blacksmithing",
  "metalworking",
  "forging",
  "casting",
  "sheet metal",
  "plumbing",
  "hydraulics",
  "pneumatics",
  "tool making",

  // 🌿 OUTDOOR & GARDEN
  "gardening",
  "landscaping",
  "hardscaping",
  "irrigation",
  "composting",
  "raised beds",
  "greenhouse",
  "hydroponics",
  "aquaponics",
  "permaculture",
  "beekeeping",
  "chicken coop",
  "shed",
  "fence",
  "gate",
  "deck",
  "patio",
  "pond",
  "fountain",
  "fire pit",
  "bbq",
  "smoker",
  "outdoor kitchen",
  "treehouse",
  "playhouse",
  "birdhouse",
  "bird feeder",
  "bee hotel",
  "insect house",
  "solar cooker",
  "rain barrel",
  "compost bin",

  // 🧪 SCIENCE & EDUCATION
  "science project",
  "stem",
  "steam",
  "experiment",
  "demonstration",
  "model",
  "demonstrator",
  "prototype",
  "invention",
  "engineering",
  "physics",
  "chemistry",
  "biology",
  "electronics",
  "robotics",
  "programming",
  "coding",
  "arduino project",
  "raspberry pi project",
  "3d printing",
  "laser cutting",
  "cnc",
  "automation",
  "rocketry",
  "aerodynamics",
  "hydraulics",
  "pneumatics",
  "renewable energy",
  "solar power",
  "wind power",
  "water power",
  "generator",
  "battery",
  "capacitor",

  // 🎭 SPECIALTY & NICHE
  "costume making",
  "cosplay",
  "prop making",
  "fx",
  "special effects",
  "makeup",
  "wig making",
  "armor making",
  "leather armor",
  "chainmail",
  "blacksmithing",
  "knife making",
  "sword making",
  "archery",
  "bow making",
  "arrow making",
  "gunsmithing",
  "wooden toys",
  "puzzles",
  "games",
  "board games",
  "tabletop",
  "musical instruments",
  "guitar",
  "violin",
  "drum",
  "flute",
  "recorder",
  "didgeridoo",
  "kalimba",
  "marimba",
  "xylophone",
  "theremin",
  "synth",
  "recording studio",
  "soundproofing",
  "acoustic treatment",
  "home theater",

  // 🏕️ SURVIVAL & BUSHCRAFT
  "survival",
  "bushcraft",
  "camping",
  "hiking",
  "backpacking",
  "knot tying",
  "shelter building",
  "fire making",
  "water purification",
  "foraging",
  "trapping",
  "fishing",
  "hunting",
  "tanning",
  "hide working",
  "primitive skills",
  "flintknapping",
  "basket making",
  "rope making",
  "net making",
  "soap making",
  "candle making",
  "preserving",
  "canning",
  "dehydrating",
  "smoking",
  "fermenting",
  "brewing",
  "distilling",
  "cheesemaking",
  "baking",
  "cooking",
  "outdoor cooking",

  // 🧩 MISCELLANEOUS
  "organization",
  "storage",
  "furniture",
  "home decor",
  "holiday",
  "christmas",
  "halloween",
  "thanksgiving",
  "easter",
  "valentine",
  "birthday",
  "party",
  "wedding",
  "baby",
  "pet",
  "dog",
  "cat",
  "bird",
  "aquarium",
  "terrarium",
  "vivarium",
  "paludarium",
  "bonsai",
  "succulent",
  "air plant",
  "kokedama",
  "book nook",
  "dollhouse",
  "miniature",
  "model",
  "diorama",
  "shadow box",
  "memory box",
  "scrapbook",
  "photo album",
  "picture frame",
  "mirror",
  "clock",
  "lamp",
  "chandelier",
  "wind chime",
  "mobile",
  "dream catcher",
  "macrame wall hanging",
  "woven wall hanging",
  "tapestry",
  "quilt",
  "afghan",
  "throw blanket",
  "pillow",
  "cushion",
  "rug",
  "doormat",
  "placemat",
  "coaster",
  "napkin",
  "tablecloth",
  "curtain",
  "blind",
  "shade",
  "screen",
  "room divider",
  "partition",
  "shelf",
  "bookcase",
  "cabinet",
  "wardrobe",
  "closet",
  "desk",
  "table",
  "chair",
  "bench",
  "stool",
  "sofa",
  "bed",
  "headboard",
  "nightstand",
  "dresser",
  "chest",
  "trunk",
  "box",
  "crate",
  "bin",
  "basket",
  "hamper",
  "organizer",
  "holder",
  "rack",
  "stand",
  "hook",
  "hanger",
  "peg",
  "knob",
  "pull",
  "handle",
  "knob",
  "hinge",
  "latch",
  "lock",
  "key",
  "sign",
  "plaque",
  "nameplate",
  "house number",
  "mailbox",
  "birdhouse",
  "bird feeder",
  "bird bath",
  "planter",
  "flower box",
  "window box",
  "herb garden",
  "vegetable garden",
  "fruit garden",
  "berry patch",
  "vineyard",
  "orchard",
  "farm",
  "homestead",
  "ranch",
  "stable",
  "barn",
  "silo",
  "windmill",
  "water wheel",
  "mill",
  "forge",
  "workshop",
  "studio",
  "atelier",
  "laboratory",
  "kitchen",
  "bathroom",
  "laundry",
  "mudroom",
  "porch",
  "patio",
  "deck",
  "balcony",
  "terrace",
  "gazebo",
  "pergola",
  "arbor",
  "trellis",
  "fence",
  "gate",
  "wall",
  "hedge",
  "border",
  "edging",
  "path",
  "walkway",
  "driveway",
  "parking",
  "garage",
  "carport",
  "shed",
  "greenhouse",
  "conservatory",
  "sunroom",
  "solarium",
  "pool",
  "spa",
  "hot tub",
  "sauna",
  "steam room",
  "shower",
  "bath",
  "vanity",
  "sink",
  "toilet",
  "bidet",
  "urinal",
  "fountain",
  "water feature",
  "pond",
  "stream",
  "waterfall",
  "aqueduct",
  "well",
  "cistern",
  "tank",
  "barrel",
  "bucket",
  "tub",
  "trough",
  "vat",
  "vat",
  "vat",
  "vat",
];

export default diyKeywords;
